### PR TITLE
Travis failure

### PR DESCRIPTION
**Pull request by tkrodriguez**

### CODE REVIEW

**Comment by tkrodriguez** [comment]
The failure appears to be within this set of merges.

```
a2c9f4d 31.01.17 10:35            Doug Simon [GR-2595] Fix mx version used in CI.
36d1fc5 31.01.17 09:03            Doug Simon [GR-2593] Cache methods for lookup in ClassfileBytecodeProvider.
ffe25b8 31.01.17 08:52            Doug Simon [GR-2440] Removed reference to Method::_jfr_towrite.
9d75033 31.01.17 06:06            Doug Simon [GR-2545] Add fast path for inlining trivial accessors.
62cbd52 31.01.17 05:14      Boris Spasojevic [GR-2444] Rewrite SL Truffle tests to not require background compilation.
6224cc5 30.01.17 17:29         Tom Rodriguez [GR-2580] Add missing ValueNode import for generated match rules.
ca81523 30.01.17 06:20   Aleksandar Prokopec [GR-2135] Add profiling for @TruffleBoundary-annotated methods.
d94ca56 30.01.17 05:00       Christian Humer [GR-1766] Remove callnode frame argument.
177563e 30.01.17 02:58           Felix Kaser [GR-2572] Remove git for darwin build.
5e0015e 28.01.17 02:31      Boris Spasojevic [GR-2444] Rewrite Truffle tests to not require background compilation.
f137082 27.01.17 09:18     Thomas Würthinger [GR-2506] Fix calculation of join IntegerStamp and refactor to always take mask and bounds into account in constructor.
dab40f5 27.01.17 08:35        Gilles Duboscq [GR-2362] Skip unnecessary Pi nodes when lowering array length.
2ba2150 26.01.17 14:01         Codrut Stancu [GR-2544] Unsafe access of edges should use wrappers in Edges class.
6415e5c 26.01.17 13:14            Doug Simon [GR-2536] Reduce dynamic usage of ResolvedJavaField.getName.
70e8985 26.01.17 08:58        Gilles Duboscq [feature] Allows to force `ANY_LOCATION` for a truffle unsafe store plugin
c1ed814 26.01.17 06:16       Stefan Anzinger [GR-2534] Use AllocatableValue in SPARC LIR instructions whenever possible.
4b8d2f7 26.01.17 06:12         Lukas Stadler [GR-2516] Cleanups/documentation in PEA
b416c07 26.01.17 02:23            Doug Simon [GR-1984] CompilerWatchdog: Swallow VMErrors.
4159a17 26.01.17 02:21            Doug Simon [GR-2407] CompilationWatchDog: Disable per default.
23acd8b 25.01.17 14:45            Doug Simon [GR-2462] [GitHub PR #245] Avoid zero-shift with AOT.
99dcac4 25.01.17 14:36            Doug Simon [GR-2526] Fixed regression in VerifyUsageWithEquals and fixed the problems it subsequently found.
71af6bb 25.01.17 09:24       Vojin Jovanovic [GR-2498] collect SVM compilation logs
69dcf99 25.01.17 06:06   Aleksandar Prokopec [GR-2477] Further improve stability of DaCapo measurements

```

**Comment by thedarkone** [comment]
Truffle frame corruption looks awfully familiar, I bet it is as simple as `jdk-9-ea+152` not having your recursive vframe_id fix (http://hg.openjdk.java.net/graal/graal-jvmci-8/rev/1ceab3d13eb8). And the trigger is probably d94ca56, since it removed automatic "heap forced" frames.

**Comment by tkrodriguez** [comment]
I think that's a good call.  It does seem to be that changeset that caused the problem to appear.  Maybe we need to disable that test until we move to a JDK that has the fix?  Any way to disable it for jdk9 only?

**Comment by tkrodriguez** [comment]
I think that's it.  That changeset does appear to expose the problem.  So truffle is slightly broken in 9 until https://bugs.openjdk.java.net/browse/JDK-8173309 makes its way into a promoted build.

**Pull request closed without merging**
